const mongoose = require('mongoose');
const Product = require('./models/Product'); // Adjust the path to your Product model

const sampleBooks = [
    {
      "imgSrc": "src/assets/book1.png",
      "title": "The Art of War",
      "author": "Sun Tzu",
      "translator": "Lionel Giles",
      "price": "120.000₫",
      "originalPrice": "150.000₫",
      "discount": "-20%",
      "rating": 4.8,
      "reviewsCount": 256,
      "soldCount": "1.5k",
      "features": ["Classic text on military strategy", "Insights into leadership and tactics", "Applicable to business and life challenges"],
      "similarBooks": [{"title": "Meditations", "imgSrc": "src/assets/meditations.png"}, {"title": "The Prince", "imgSrc": "src/assets/the_prince.png"}],
      "galleryImages": ["src/assets/book1_thumb1.png", "src/assets/book1_thumb2.png"],
      "sku": "ART12345",
      "ageGroup": "Adults",
      "supplier": "Ancient Wisdom Publishers",
      "publisher": "Classic Texts",
      "publicationYear": 1910,
      "language": "English",
      "weight": "250g",
      "dimensions": "21 x 14 x 1.5 cm",
      "pages": 200,
      "binding": "Paperback"
    },
    {
      "imgSrc": "src/assets/book2.png",
      "title": "Atomic Habits",
      "author": "James Clear",
      "price": "180.000₫",
      "originalPrice": "200.000₫",
      "discount": "-10%",
      "rating": 4.9,
      "reviewsCount": 500,
      "soldCount": "3k",
      "features": ["Proven framework for building habits", "Practical strategies for success", "Popular self-help book"],
      "similarBooks": [{"title": "Deep Work", "imgSrc": "src/assets/deep_work.png"}, {"title": "The Power of Habit", "imgSrc": "src/assets/power_habit.png"}],
      "galleryImages": ["src/assets/book2_thumb1.png", "src/assets/book2_thumb2.png"],
      "sku": "HAB12345",
      "ageGroup": "Adults",
      "supplier": "Motivation Publishers",
      "publisher": "Success Books",
      "publicationYear": 2018,
      "language": "English",
      "weight": "300g",
      "dimensions": "22 x 14 x 2 cm",
      "pages": 320,
      "binding": "Hardcover"
    },
    {
      "imgSrc": "src/assets/book3.png",
      "title": "1984",
      "author": "George Orwell",
      "price": "90.000₫",
      "originalPrice": "120.000₫",
      "discount": "-25%",
      "rating": 4.7,
      "reviewsCount": 780,
      "soldCount": "10k",
      "features": ["Dystopian novel", "Critique of totalitarianism", "A literary classic"],
      "similarBooks": [{"title": "Brave New World", "imgSrc": "src/assets/brave_new_world.png"}, {"title": "Fahrenheit 451", "imgSrc": "src/assets/fahrenheit_451.png"}],
      "galleryImages": ["src/assets/book3_thumb1.png", "src/assets/book3_thumb2.png"],
      "sku": "DYS12345",
      "ageGroup": "Adults",
      "supplier": "Dystopian Reads",
      "publisher": "Literary Classics",
      "publicationYear": 1949,
      "language": "English",
      "weight": "270g",
      "dimensions": "20 x 13 x 2 cm",
      "pages": 328,
      "binding": "Paperback"
    },
    {
      "imgSrc": "src/assets/book4.png",
      "title": "To Kill a Mockingbird",
      "author": "Harper Lee",
      "price": "100.000₫",
      "originalPrice": "140.000₫",
      "discount": "-28%",
      "rating": 4.9,
      "reviewsCount": 860,
      "soldCount": "15k",
      "features": ["Pulitzer Prize-winning novel", "Exploration of racial injustice", "A timeless classic"],
      "similarBooks": [{"title": "Go Set a Watchman", "imgSrc": "src/assets/go_set_watchman.png"}, {"title": "The Help", "imgSrc": "src/assets/the_help.png"}],
      "galleryImages": ["src/assets/book4_thumb1.png", "src/assets/book4_thumb2.png"],
      "sku": "CLA12345",
      "ageGroup": "Teens and Adults",
      "supplier": "Classic Reads",
      "publisher": "Timeless Classics",
      "publicationYear": 1960,
      "language": "English",
      "weight": "320g",
      "dimensions": "21 x 14 x 2.5 cm",
      "pages": 336,
      "binding": "Hardcover"
    },
    {
      "imgSrc": "src/assets/book5.png",
      "title": "Sapiens: A Brief History of Humankind",
      "author": "Yuval Noah Harari",
      "price": "220.000₫",
      "originalPrice": "250.000₫",
      "discount": "-12%",
      "rating": 4.8,
      "reviewsCount": 980,
      "soldCount": "12k",
      "features": ["Explores the history of humankind", "Insight into societal evolution", "Thought-provoking perspectives"],
      "similarBooks": [{"title": "Homo Deus", "imgSrc": "src/assets/homo_deus.png"}, {"title": "Guns, Germs, and Steel", "imgSrc": "src/assets/guns_germs.png"}],
      "galleryImages": ["src/assets/book5_thumb1.png", "src/assets/book5_thumb2.png"],
      "sku": "HIS12345",
      "ageGroup": "Adults",
      "supplier": "Knowledge Publishers",
      "publisher": "Harari Books",
      "publicationYear": 2014,
      "language": "English",
      "weight": "380g",
      "dimensions": "24 x 16 x 3 cm",
      "pages": 512,
      "binding": "Hardcover"
    },
    {
      "imgSrc": "src/assets/book6.png",
      "title": "Becoming",
      "author": "Michelle Obama",
      "price": "180.000₫",
      "originalPrice": "200.000₫",
      "discount": "-10%",
      "rating": 4.9,
      "reviewsCount": 600,
      "soldCount": "4k",
      "features": ["Memoir of former First Lady", "Inspiration and resilience", "Bestselling autobiography"],
      "similarBooks": [{"title": "My Life", "imgSrc": "src/assets/my_life.png"}, {"title": "The Audacity of Hope", "imgSrc": "src/assets/audacity_hope.png"}],
      "galleryImages": ["src/assets/book6_thumb1.png", "src/assets/book6_thumb2.png"],
      "sku": "BEC12345",
      "ageGroup": "Adults",
      "supplier": "Penguin Random House",
      "publisher": "Crown Publishing",
      "publicationYear": 2018,
      "language": "English",
      "weight": "420g",
      "dimensions": "23 x 16 x 2.8 cm",
      "pages": 448,
      "binding": "Hardcover"
    },
    {
        "imgSrc": "src/assets/book1.png",
        "title": "The Art of War",
        "author": "Sun Tzu",
        "translator": "Lionel Giles",
        "price": "120.000₫",
        "originalPrice": "150.000₫",
        "discount": "-20%",
        "rating": 4.8,
        "reviewsCount": 256,
        "soldCount": "1.5k",
        "features": ["Classic text on military strategy", "Insights into leadership and tactics", "Applicable to business and life challenges"],
        "similarBooks": [{"title": "Meditations", "imgSrc": "src/assets/meditations.png"}, {"title": "The Prince", "imgSrc": "src/assets/the_prince.png"}],
        "galleryImages": ["src/assets/book1_thumb1.png", "src/assets/book1_thumb2.png"],
        "sku": "ART12345",
        "ageGroup": "Adults",
        "supplier": "Ancient Wisdom Publishers",
        "publisher": "Classic Texts",
        "publicationYear": 1910,
        "language": "English",
        "weight": "250g",
        "dimensions": "21 x 14 x 1.5 cm",
        "pages": 200,
        "binding": "Paperback"
      },
      {
        "imgSrc": "src/assets/book1.png",
        "title": "The Art of War",
        "author": "Sun Tzu",
        "translator": "Lionel Giles",
        "price": "120.000₫",
        "originalPrice": "150.000₫",
        "discount": "-20%",
        "rating": 4.8,
        "reviewsCount": 256,
        "soldCount": "1.5k",
        "features": ["Classic text on military strategy", "Insights into leadership and tactics", "Applicable to business and life challenges"],
        "similarBooks": [{"title": "Meditations", "imgSrc": "src/assets/meditations.png"}, {"title": "The Prince", "imgSrc": "src/assets/the_prince.png"}],
        "galleryImages": ["src/assets/book1_thumb1.png", "src/assets/book1_thumb2.png"],
        "sku": "ART12345",
        "ageGroup": "Adults",
        "supplier": "Ancient Wisdom Publishers",
        "publisher": "Classic Texts",
        "publicationYear": 1910,
        "language": "English",
        "weight": "250g",
        "dimensions": "21 x 14 x 1.5 cm",
        "pages": 200,
        "binding": "Paperback"
      },
      {
        "imgSrc": "src/assets/book1.png",
        "title": "The Art of War",
        "author": "Sun Tzu",
        "translator": "Lionel Giles",
        "price": "120.000₫",
        "originalPrice": "150.000₫",
        "discount": "-20%",
        "rating": 4.8,
        "reviewsCount": 256,
        "soldCount": "1.5k",
        "features": ["Classic text on military strategy", "Insights into leadership and tactics", "Applicable to business and life challenges"],
        "similarBooks": [{"title": "Meditations", "imgSrc": "src/assets/meditations.png"}, {"title": "The Prince", "imgSrc": "src/assets/the_prince.png"}],
        "galleryImages": ["src/assets/book1_thumb1.png", "src/assets/book1_thumb2.png"],
        "sku": "ART12345",
        "ageGroup": "Adults",
        "supplier": "Ancient Wisdom Publishers",
        "publisher": "Classic Texts",
        "publicationYear": 1910,
        "language": "English",
        "weight": "250g",
        "dimensions": "21 x 14 x 1.5 cm",
        "pages": 200,
        "binding": "Paperback"
      },
      {
        "imgSrc": "src/assets/book1.png",
        "title": "The Art of War",
        "author": "Sun Tzu",
        "translator": "Lionel Giles",
        "price": "120.000₫",
        "originalPrice": "150.000₫",
        "discount": "-20%",
        "rating": 4.8,
        "reviewsCount": 256,
        "soldCount": "1.5k",
        "features": ["Classic text on military strategy", "Insights into leadership and tactics", "Applicable to business and life challenges"],
        "similarBooks": [{"title": "Meditations", "imgSrc": "src/assets/meditations.png"}, {"title": "The Prince", "imgSrc": "src/assets/the_prince.png"}],
        "galleryImages": ["src/assets/book1_thumb1.png", "src/assets/book1_thumb2.png"],
        "sku": "ART12345",
        "ageGroup": "Adults",
        "supplier": "Ancient Wisdom Publishers",
        "publisher": "Classic Texts",
        "publicationYear": 1910,
        "language": "English",
        "weight": "250g",
        "dimensions": "21 x 14 x 1.5 cm",
        "pages": 200,
        "binding": "Paperback"
      },
      {
        "imgSrc": "src/assets/book1.png",
        "title": "The Art of War",
        "author": "Sun Tzu",
        "translator": "Lionel Giles",
        "price": "120.000₫",
        "originalPrice": "150.000₫",
        "discount": "-20%",
        "rating": 4.8,
        "reviewsCount": 256,
        "soldCount": "1.5k",
        "features": ["Classic text on military strategy", "Insights into leadership and tactics", "Applicable to business and life challenges"],
        "similarBooks": [{"title": "Meditations", "imgSrc": "src/assets/meditations.png"}, {"title": "The Prince", "imgSrc": "src/assets/the_prince.png"}],
        "galleryImages": ["src/assets/book1_thumb1.png", "src/assets/book1_thumb2.png"],
        "sku": "ART12345",
        "ageGroup": "Adults",
        "supplier": "Ancient Wisdom Publishers",
        "publisher": "Classic Texts",
        "publicationYear": 1910,
        "language": "English",
        "weight": "250g",
        "dimensions": "21 x 14 x 1.5 cm",
        "pages": 200,
        "binding": "Paperback"
      },
      {
        "imgSrc": "src/assets/book1.png",
        "title": "The Art of War",
        "author": "Sun Tzu",
        "translator": "Lionel Giles",
        "price": "120.000₫",
        "originalPrice": "150.000₫",
        "discount": "-20%",
        "rating": 4.8,
        "reviewsCount": 256,
        "soldCount": "1.5k",
        "features": ["Classic text on military strategy", "Insights into leadership and tactics", "Applicable to business and life challenges"],
        "similarBooks": [{"title": "Meditations", "imgSrc": "src/assets/meditations.png"}, {"title": "The Prince", "imgSrc": "src/assets/the_prince.png"}],
        "galleryImages": ["src/assets/book1_thumb1.png", "src/assets/book1_thumb2.png"],
        "sku": "ART12345",
        "ageGroup": "Adults",
        "supplier": "Ancient Wisdom Publishers",
        "publisher": "Classic Texts",
        "publicationYear": 1910,
        "language": "English",
        "weight": "250g",
        "dimensions": "21 x 14 x 1.5 cm",
        "pages": 200,
        "binding": "Paperback"
      }
  ];
  
  
const insertSampleData = async () => {
  try {
    await mongoose.connect('mongodb+srv://trantuananhbo2093:FPa18YPpQAi7VkSM@cluster0.lydwo.mongodb.net/bookDB?retryWrites=true&w=majority&appName=Cluster0'); // Replace with your MongoDB URI
    console.log('Connected to MongoDB');

    await Product.deleteMany(); // Clear the existing collection
    console.log('Existing data cleared.');

    await Product.insertMany(sampleBooks);
    console.log('Sample data inserted successfully.');

    mongoose.disconnect();
    console.log('Disconnected from MongoDB');
  } catch (error) {
    console.error('Error inserting sample data:', error);
    mongoose.disconnect();
  }
};

insertSampleData();
